### PR TITLE
nvme: Updated latest offset value for Interrupt Mask Clear register

### PR DESCRIPTION
**Pull request by Arunpandian15**
Signed-off-by: Arunpandian J <apj.arun@samsung.com>

### CODE REVIEW

**Comment by Arunpandian15** [comment]
You can check this on NVMe Base spec 2.0, section 3.1.3

**Comment by igaw** [comment]
Spec seems to be inconsistent or I don't get it.

In Figure 35, the offset for INTMC is 0xf but in chapter 3.1.3.4 the offset is listed as 0x10.

@hreinecke, @keithbusch any ideas what's going on here?

**Comment by Arunpandian15** [comment]
Hi @igaw 
I think 0x10 is the correct value
INTMS offset is 0xC and size is 4 then INTMC offset will come as 0x10
Please confirm then we can close this PR.
Thanks!

**Comment by igaw** [comment]
With the register size of 4 and INTMS is at offset 0xc, INTMC can't start at 0xf. I agree with you on that. This looks like a typo in the spec. The Linux kernel also defines at 0x10

```c
enum {
        NVME_REG_CAP    = 0x0000,       /* Controller Capabilities */
        NVME_REG_VS     = 0x0008,       /* Version */
        NVME_REG_INTMS  = 0x000c,       /* Interrupt Mask Set */
        NVME_REG_INTMC  = 0x0010,       /* Interrupt Mask Clear */
```

**Pull request closed without merging**
