### PR TITLE
meson + ccan configuration fixes

### PR DESCRIPTION
**Pull request by jk-ozlabs**
These changes fix a couple of issues with the ccan configuration system,
reported by @birkelund .

### CODE REVIEW

**Comment by birkelund** [comment]
Right, it was just a misspelled named in meson, I missed that.

Thanks!, LGTM!

**Comment by igaw** [comment]
Oh, I screwed it up. When I merged PR#8 I didn't see it was based on PR#74. So PR#74 was not supposed to go in without reviewing. Sorry about that.

@jk-ozlabs what's the way forward? Should I revert PR#74 and apply this PR on top?

**Comment by jk-ozlabs** [comment]
@iagw: working on a fix now - I'll see if I can get the revert done without breaking the build in-between. Will update this PR when I have something workable :)

**Comment by jk-ozlabs** [comment]
OK, this has the reverts integrated with the fixes so we don't break the build in-between. The changes are no longer obvious though.

If you'd prefer the non-atomic series, which is a bit cleaner, I've also pushed that in my [ccan-fix-breaky](https://github.com/jk-ozlabs/libnvme/tree/ccan-fix-breaky) branch.

**Comment by igaw** [comment]
BTW, with the recent changes how deal with ccan and the header cleanup (removing le32_to_cpu) we broke nvme-cli. I think we need to add ccan to nvme-cli as well. Care to send a PR for it, since you seem to have a way better understanding in these things than I do :)

**Comment by jk-ozlabs** [comment]
Yep, I can definitely have a go at fixing that!

**Pull request merged**
