### PR TITLE
[libnvme] Add uuidx parm to get log page API

### PR DESCRIPTION
**Pull request by jeffreyalien**
Add uuidx parm to nvme_get_log_page and nvme_get_log_page_padded functions

Signed-off-by: Jeff Lien <jeff.lien@wdc.com>

### CODE REVIEW

**Comment by igaw** [comment]
Looks okay, but I am wondering if it wouldn't be better to turn the argument list into an `struct args`. `nvme_get_log_pages()` and `nvme_get_log_pages_padded()` are basically a convenience wrapper for `nvme_get_log()`. Since we have the `struct args` for `nvme_get_log()` we might just want to do the same for `nvme_get_log_pages()`.

If we do this I would also merge `nvme_get_log_pages()` and `nvme_get_log_pages_padded()` into one function and make the padded feature enabled by a member in the struct args.

**Comment by hreinecke** [comment]
The whole point in having a 'struct args' is that it's easy to create wrappers and that you do _not_ have to modify existing wrappers all the time.
Hence please add a new wrapper ('nvme_get_log_pages_uuidx()' ?) instead of updating the existing one.

**Comment by jeffreyalien** [comment]
Yea, I was thinking the same thing as I made the change.  I should have gone with that thought.  I'll make that change along with combining those 2 get log functions.

**Comment by jeffreyalien** [comment]
@igaw @hreinecke  Please review updated pull request.  Thanks.

**Review by hreinecke — APPROVED** [review]
Much better.

**Comment by igaw** [comment]
Removed nvme_get_log_page_padded() from libnvme.map.

**Pull request merged**
