### PR TITLE
TLS keys handling

### PR DESCRIPTION
**Pull request by igaw**
Refactor and extend the PSK API and decouple the key store operations from the JSON parsing.

Fixes: #890

### CODE REVIEW

**Comment by hreinecke** [comment]
Please check also https://github.com/linux-nvme/libnvme/pull/896 ; we should probably combine these two pull requests.

**Comment by igaw** [comment]
I found that the config.json and `connect-all` doesn't go well together. `connect-all` wants really to use discovery controllers to figure out what to connect. It uses parts of the info the config.json to create a discovery controller but with tls enabled this really doesn't work against the Linux target implementation.

Maybe `connect` should connect to all controllers listed in config.json without the discovery part. `connect-all` turned into a monster and we have to look at it later.  Anyway, these changes here are working fine, it's just nvme-cli needs to be updated.

**Comment by igaw** [comment]
decided to rip out the retained key handling completely. nice feature which likely no one is going to use.

**Comment by igaw** [comment]
So finally got all use cases working:
- connect using config.json only (no discovery etc, just the entries in the config)
- connect with key pass directly from command line 
- connect with key already in keystore

Note, nvme-cli also needs some changes which I am not sure how to handle in the details. I suggest we discuss this in the nvme-cli PR though.

**Pull request merged**
