### PR TITLE
meson: small fixes

### PR DESCRIPTION
**Pull request by birkelund**

### CODE REVIEW

**Comment by igaw** [comment]
Can you please explain what you try to fix. I am worried about the current_build_dir() returning an absolute path. I understood that adding absolute paths is not recommended in meson (maybe I got this part wrong). So please help me to understand what is broken and why this fix is correct.

**Comment by birkelund** [comment]
The `declare_dependency` should not include `ccan/` and `.` as include directories - since these are internal and may clash with the upper project - only the `src/` dir should be added to the list of searchable paths (`-I`).

You are right about the paths for the `-include`. Since gcc's `-include` also looks in the search path, I shouldn't remove `.` in patch 2. Instead, drop that patch and just make sure that we do not leak the ccan or project includedirs.

**Comment by igaw** [comment]
Sorry! I didn't realize you updated the PR. Looks good!

**Comment by birkelund** [comment]
> Sorry! I didn't realize you updated the PR. Looks good!

No problem, thanks for merging :)

**Pull request merged**
