### PR TITLE
Rework scanning logic

### PR DESCRIPTION
**Pull request by hreinecke**
Hi all,

this patchset reworks the scanning logic to first iterate over all controllers, and then over all subsystems.
The original method of iterating over subsystems only had the drawback that the 'host' is only specified at the controller level (via the 'hostnqn' and 'hostid' attributes), but the subsystem structure needs to be attached to an existing host structure, making scanning the entire topology really awkward.

### CODE REVIEW

**Comment by igaw** [comment]
It would be an excellent opportunity to add some documentation to the functions you touch.

**Comment by igaw** [comment]
We should add this change before the 1.0 release as a function gets removed from the API.

**Comment by keithbusch** [comment]
This looks alright. I'd like to give it a test on complex topologies, but I honestly don't think I'll be able to until the new year. If you've tested with a mix of multipath and single path with at least two transports (ex: pcie & tcp), then that's probably good enough.

**Comment by igaw** [comment]
Rebased to the current head.

**Comment by igaw** [comment]
I've setup a TCP target with two different subsystems. 'nvme list -v' crashes with

```
0x000000000048fc6c in nvme_ns_get_name (n=0x0) at ../subprojects/libnvme/src/nvme/tree.c:1390
1390            return n->name;
Missing separate debuginfos, use: zypper install libhugetlbfs-debuginfo-2.20-3.3.1.x86_64 libopenssl1_1-debuginfo-1.1.1d-11.23.1.x86_64 libuuid1-debuginfo-2.33.1-4.13.1.x86_64 libz1-debuginfo-1.2.11-3.21.1.x86_64
(gdb) bt
#0  0x000000000048fc6c in nvme_ns_get_name (n=0x0) at ../subprojects/libnvme/src/nvme/tree.c:1390
#1  0x0000000000438b15 in nvme_show_detailed_list (r=0x70c730) at ../nvme-print.c:6707
#2  0x0000000000439bc8 in nvme_show_list_items (r=0x70c730, flags=VERBOSE) at ../nvme-print.c:6908
#3  0x000000000040ef4e in list (argc=2, argv=0x7fffffffe370, cmd=0x6e9580 <list_cmd>, plugin=0x6ea360 <builtin>) at ../nvme.c:2349
#4  0x000000000043ccc1 in handle_plugin (argc=2, argv=0x7fffffffe370, plugin=0x6ea360 <builtin>) at ../plugin.c:155
#5  0x000000000041e7fa in main (argc=3, argv=0x7fffffffe368) at ../nvme.c:7294
```

**Comment by martin-belanger** [comment]
We may be able to get more info by disabling optimization. In other words, run meson with this and rebuild.
```
meson .build -Dbuildtype=debug
```

**Comment by igaw** [comment]
That bt is with O=g and debug build. In the meantime the host got properly confused with a bunch of stale nvme entries. Updating kernel right now and retrying...

**Comment by igaw** [comment]
A reboot with a fresh kernel (no stale nvme entries) and all looks good.

```
dolin:~/nvme-cli/:[0]# .build/nvme list -v
Subsystem        Subsystem-NQN                                                                                    Controllers
---------------- ------------------------------------------------------------------------------------------------ ----------------
nvme-subsys9     nqn.2014-08.org.nvmexpress:NVMf:uuid:de63429f-50a4-4e03-ade6-0be27b75be77                        nvme9, nvme10
nvme-subsys3     nqn.1992-08.com.netapp:sn.d646dc63336511e995cb00a0988fb732:subsystem.nvme-svm-dolin-ana_subsystem_mwilck nvme8, nvme7, nvme4, nvme3
nvme-subsys11    nqn.2014-08.org.nvmexpress:NVMf:uuid:7a7aa300-7545-11ec-93c5-40a8f0343914                        nvme12, nvme11
nvme-subsys1     nqn.1992-08.com.netapp:sn.d646dc63336511e995cb00a0988fb732:subsystem.nvme-svm-dolin-ana_subsystem nvme6, nvme5, nvme2, nvme1

Device   SN                   MN                                       FR       TxPort Address        Subsystem    Namespaces      
-------- -------------------- ---------------------------------------- -------- ------ -------------- ------------ ----------------
nvme9    2c5579124a387f63f47f Linux                                    5.14.0-r tcp    traddr=10.161.8.24,trsvcid=4420 nvme-subsys9 nvme9n1
nvme10   2c5579124a387f63f47f Linux                                    5.14.0-r tcp    traddr=10.161.8.24,trsvcid=4421 nvme-subsys9 nvme9n1
nvme8    80-AABMxwn3xAAAAAAAF NetApp ONTAP Controller                  FFFFFFFF fc     traddr=nn-0x201700a09890f5bf:pn-0x201900a09890f5bf,host_traddr=nn-0x200000109b579ef6:pn-0x100000109b579ef6 nvme-subsys3 nvme3n1
nvme7    80-AABMxwn3xAAAAAAAF NetApp ONTAP Controller                  FFFFFFFF fc     traddr=nn-0x201700a09890f5bf:pn-0x201800a09890f5bf,host_traddr=nn-0x200000109b579ef6:pn-0x100000109b579ef6 nvme-subsys3 nvme3n1
nvme4    80-AABMxwn3xAAAAAAAF NetApp ONTAP Controller                  FFFFFFFF fc     traddr=nn-0x201700a09890f5bf:pn-0x201900a09890f5bf,host_traddr=nn-0x200000109b579ef3:pn-0x100000109b579ef3 nvme-subsys3 nvme3n1
nvme3    80-AABMxwn3xAAAAAAAF NetApp ONTAP Controller                  FFFFFFFF fc     traddr=nn-0x201700a09890f5bf:pn-0x201800a09890f5bf,host_traddr=nn-0x200000109b579ef3:pn-0x100000109b579ef3 nvme-subsys3 nvme3n1
nvme12   5d277b6204e2782df982 Linux                                    5.14.0-r tcp    traddr=10.161.8.24,trsvcid=4423 nvme-subsys11 nvme11n1
nvme11   5d277b6204e2782df982 Linux                                    5.14.0-r tcp    traddr=10.161.8.24,trsvcid=4422 nvme-subsys11 nvme11n1
nvme6    80-AABMxwn3xAAAAAAAB NetApp ONTAP Controller                  FFFFFFFF fc     traddr=nn-0x201700a09890f5bf:pn-0x201900a09890f5bf,host_traddr=nn-0x200000109b579ef6:pn-0x100000109b579ef6 nvme-subsys1 nvme1n2, nvme1n1
nvme5    80-AABMxwn3xAAAAAAAB NetApp ONTAP Controller                  FFFFFFFF fc     traddr=nn-0x201700a09890f5bf:pn-0x201800a09890f5bf,host_traddr=nn-0x200000109b579ef6:pn-0x100000109b579ef6 nvme-subsys1 nvme1n2, nvme1n1
nvme2    80-AABMxwn3xAAAAAAAB NetApp ONTAP Controller                  FFFFFFFF fc     traddr=nn-0x201700a09890f5bf:pn-0x201900a09890f5bf,host_traddr=nn-0x200000109b579ef3:pn-0x100000109b579ef3 nvme-subsys1 nvme1n2, nvme1n1
nvme1    80-AABMxwn3xAAAAAAAB NetApp ONTAP Controller                  FFFFFFFF fc     traddr=nn-0x201700a09890f5bf:pn-0x201800a09890f5bf,host_traddr=nn-0x200000109b579ef3:pn-0x100000109b579ef3 nvme-subsys1 nvme1n2, nvme1n1

Device       Generic      NSID     Usage                      Format           Controllers     
------------ ------------ -------- -------------------------- ---------------- ----------------
nvme9n1      ng9n1        1          2.25  GB /   2.25  GB    512   B +  0 B   nvme9, nvme10
nvme3n1      ng3n1        1         34.36  GB /  34.36  GB      4 KiB +  0 B   nvme8, nvme7, nvme4, nvme3
nvme11n1     ng11n1       2        104.86  MB / 104.86  MB    512   B +  0 B   nvme12, nvme11
nvme1n2      ng1n2        2         34.36  GB /  34.36  GB      4 KiB +  0 B   nvme6, nvme5, nvme2, nvme1
nvme1n1      ng1n1        1         34.36  GB /  34.36  GB      4 KiB +  0 B   nvme6, nvme5, nvme2, nvme1
dolin:~/nvme-cli/:[0]# .build/nvme list-subsys
nvme-subsys9 - NQN=nqn.2014-08.org.nvmexpress:NVMf:uuid:de63429f-50a4-4e03-ade6-0be27b75be77
\
 +- nvme9 tcp traddr=10.161.8.24,trsvcid=4420 live
 +- nvme10 tcp traddr=10.161.8.24,trsvcid=4421 live
nvme-subsys3 - NQN=nqn.1992-08.com.netapp:sn.d646dc63336511e995cb00a0988fb732:subsystem.nvme-svm-dolin-ana_subsystem_mwilck
\
 +- nvme8 fc traddr=nn-0x201700a09890f5bf:pn-0x201900a09890f5bf,host_traddr=nn-0x200000109b579ef6:pn-0x100000109b579ef6 live
 +- nvme7 fc traddr=nn-0x201700a09890f5bf:pn-0x201800a09890f5bf,host_traddr=nn-0x200000109b579ef6:pn-0x100000109b579ef6 live
 +- nvme4 fc traddr=nn-0x201700a09890f5bf:pn-0x201900a09890f5bf,host_traddr=nn-0x200000109b579ef3:pn-0x100000109b579ef3 live
 +- nvme3 fc traddr=nn-0x201700a09890f5bf:pn-0x201800a09890f5bf,host_traddr=nn-0x200000109b579ef3:pn-0x100000109b579ef3 live
nvme-subsys11 - NQN=nqn.2014-08.org.nvmexpress:NVMf:uuid:7a7aa300-7545-11ec-93c5-40a8f0343914
\
 +- nvme12 tcp traddr=10.161.8.24,trsvcid=4423 live
 +- nvme11 tcp traddr=10.161.8.24,trsvcid=4422 live
nvme-subsys1 - NQN=nqn.1992-08.com.netapp:sn.d646dc63336511e995cb00a0988fb732:subsystem.nvme-svm-dolin-ana_subsystem
\
 +- nvme6 fc traddr=nn-0x201700a09890f5bf:pn-0x201900a09890f5bf,host_traddr=nn-0x200000109b579ef6:pn-0x100000109b579ef6 live
 +- nvme5 fc traddr=nn-0x201700a09890f5bf:pn-0x201800a09890f5bf,host_traddr=nn-0x200000109b579ef6:pn-0x100000109b579ef6 live
 +- nvme2 fc traddr=nn-0x201700a09890f5bf:pn-0x201900a09890f5bf,host_traddr=nn-0x200000109b579ef3:pn-0x100000109b579ef3 live
 +- nvme1 fc traddr=nn-0x201700a09890f5bf:pn-0x201800a09890f5bf,host_traddr=nn-0x200000109b579ef3:pn-0x100000109b579ef3 live

```

**Comment by igaw** [comment]
And for PCI it also looks good:

```
carbon:/home/wagi/work/nvme-cli/.build # ./nvme list
Node                  SN                   Model                                    Namespace Usage                      Format           FW Rev  
--------------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
nvme0n1               49MA23BZK03N         KXG60ZNV512G NVMe TOSHIBA 512GB          1         512.11  GB / 512.11  GB    512   B +  0 B   10604107
carbon:/home/wagi/work/nvme-cli/.build # ./nvme list -v
Subsystem        Subsystem-NQN                                                                                    Controllers
---------------- ------------------------------------------------------------------------------------------------ ----------------
nvme-subsys0     nqn.2017-03.jp.co.toshiba:KXG60ZNV512G NVMe TOSHIBA 512GB:49MA23BZK03N                           nvme0

Device   SN                   MN                                       FR       TxPort Address        Subsystem    Namespaces      
-------- -------------------- ---------------------------------------- -------- ------ -------------- ------------ ----------------
nvme0    49MA23BZK03N         KXG60ZNV512G NVMe TOSHIBA 512GB          10604107 pcie   0000:3d:00.0   nvme-subsys0 nvme0n1

Device       Generic      NSID     Usage                      Format           Controllers     
------------ ------------ -------- -------------------------- ---------------- ----------------
nvme0n1      ng0n1        1        512.11  GB / 512.11  GB    512   B +  0 B   nvme0
carbon:/home/wagi/work/nvme-cli/.build # ./nvme list-subsys 
nvme-subsys0 - NQN=nqn.2017-03.jp.co.toshiba:KXG60ZNV512G NVMe TOSHIBA 512GB:49MA23BZK03N
\
 +- nvme0 pcie 0000:3d:00.0 live
```

**Pull request merged**
