### PR TITLE
build: Add subpackages contents to .gitignore

### PR DESCRIPTION
**Pull request by sc108-lee**
we just need to maintain .wrap files for dependencies

Signed-off-by: Steven Seungcheol Lee <sc108.lee@samsung.com>

### CODE REVIEW

**Comment by sc108-lee** [comment]
@igaw I saw your commits for nvme-cli like below
https://github.com/linux-nvme/nvme-cli/commit/7a0217ffa27756b94f0c18bd1baf3ab33164ed92

you are going to add more dependencies as wrap file, so how about to change .gitignore as this PR?
so we don't need to care when new subproject comes

**Comment by igaw** [comment]
Ah nice, didn't know about the '!' feature. Yes let's do this.

**Comment by igaw** [comment]
BTW, I've picked your patch for my nvme-cli PR.

**Comment by sc108-lee** [comment]
cool :)
thanks for picking it up

**Pull request merged**
