### PR TITLE
test: Print passed info of the test

### PR DESCRIPTION
**Pull request by Arunpandian15**
Introducing log helper function for identify, logs.

Signed-off-by: Arunpandian J <apj.arun@samsung.com>

### CODE REVIEW

**Comment by igaw** [comment]
I wonder if you could not just introduce a helper function which takes the string to be printed and the error code and generically adds 'PASSED' when `err == 0` and 'FAILED' for `err != 0`.

**Comment by igaw** [comment]
Something like:

```patch
+#include <stdarg.h>
+#include <stdlib.h>
+
 #include <libnvme.h>
 
 #include <ccan/endian/endian.h>
@@ -34,6 +37,22 @@ static bool nvme_match_subsysnqn_filter(nvme_subsystem_t s,
        return true;
 }
 
+void __attribute__((format(printf, 2, 3)))
+log_result(int ret, const char *format, ...)
+{
+       va_list ap;
+       char *msg;
+
+       va_start(ap, format);
+       if (vasprintf(&msg, format, ap) == -1)
+               msg = NULL;
+       va_end(ap);
+
+       printf("%s: %s", ret ? "FAILED" : "PASSED", msg);
+
+       free(msg);
+}
+
```

**Comment by igaw** [comment]
This doesn't block the 1.0 release, so let's move it to 1.1

**Comment by Arunpandian15** [comment]
@igaw 
suggestion is to print like below 
printf("%s: %x\n", ret ? "ERROR: Sanitize Log" : "PASSED: Sanitize Log", ret);

**Comment by igaw** [comment]
Yes, I think having every string twice like

```c
        ret = nvme_get_log_device_self_test(fd, &st);                                                                                                                   
        if (!ret)                                                                                                                                                       
                printf("  PASSED: Device Self Test\n");                                                                                                                 
        else                                                                                                                                                            
                printf("  ERROR: Device Self Test:%x\n", ret);   
```

a bit silly. So by introducing a log helper would avoid having every string twice just differently prefixed.

**Comment by igaw** [comment]
Could  you introduce the log_result() function I posted a few comments above and use it instead of open coding everything? That would reduce the code duplication even move :)

**Comment by igaw** [comment]
I was wonder if the change below would be an option? But understand this test is actually used for hardware testing so I am reluctant to change it unless you are happy with it.

```
diff --git a/test/test.c b/test/test.c
index 858cb381fabb..19081c3d1b86 100644
--- a/test/test.c
+++ b/test/test.c
@@ -20,10 +20,31 @@
 #include <stdbool.h>
 #include <inttypes.h>
 #include <uuid.h>
+#include <stdarg.h>
+#include <stdlib.h>
 #include <libnvme.h>
 
 #include <ccan/endian/endian.h>
 
+void __attribute__((format(printf, 3, 4)))
+log_result(int ret, const char *name, const char *format, ...)
+{
+	va_list ap;
+	char *msg;
+
+	va_start(ap, format);
+	if (vasprintf(&msg, format, ap) == -1)
+		msg = NULL;
+	va_end(ap);
+
+	if (!ret)
+		printf("PASSED: %s%s", name, msg);
+	else
+		printf("ERROR:  %s:%x\n", name, ret);
+
+	free(msg);
+}
+
 static bool nvme_match_subsysnqn_filter(nvme_subsystem_t s,
 		nvme_ctrl_t c, nvme_ns_t ns, void *f_args)
 {
@@ -89,131 +110,80 @@ static int test_ctrl(nvme_ctrl_t c)
 	printf("  model:%-.40s\n", id.mn);
 
 	ret = nvme_identify_allocated_ns_list(fd, 0, &ns_list);
-	printf("%s: %x\n", ret ? "ERROR: Allocated NS List" : "PASSED: Allocated NS List", ret);
+	log_result(ret, "Allocated NS List", "\n");
 	ret = nvme_identify_active_ns_list(fd, 0, &ns_list);
-	printf("%s: %x\n", ret ? "ERROR: Active NS List" : "PASSED: Active NS List", ret);
+	log_result(ret, "Active NS List", "\n");
 	ret = nvme_identify_ctrl_list(fd, 0, &ctrlist);
-	printf("%s: %x\n", ret ? "ERROR: Ctrl List" : "PASSED: Ctrl List", ret);
+	log_result(ret, "Ctrl List", "\n");
 	ret = nvme_identify_nsid_ctrl_list(fd, 1, 0, &ctrlist);
-	printf("%s: %x\n", ret ? "ERROR: NSID Ctrl List" : "PASSED: NSID Ctrl List", ret);
+	log_result(ret, "NSID Ctrl List", "\n");
 	ret = nvme_identify_primary_ctrl(fd, 0, &prim);
-	printf("%s: %x\n", ret ? "ERROR: Identify Primary" : "PASSED: Identify Primary", ret);
+	log_result(ret, "Identify Primary", "\n");
 	ret = nvme_identify_secondary_ctrl_list(fd, 1, 0, &sec);
-	printf("%s: %x\n", ret ? "ERROR: Identify Secondary" : "PASSED: Identify Secondary", ret);
+	log_result(ret, "Identify Secondary", "\n");
 	ret = nvme_identify_ns_granularity(fd, &gran);
-	printf("%s: %x\n", ret ? "ERROR: Identify NS granularity" : "PASSED: Identify NS granularity", ret);
+	log_result(ret, "Identify NS granularity", "\n");
 	ret = nvme_identify_uuid(fd, &uuid);
-	printf("%s: %x\n", ret ? "ERROR: Identify UUID List" : "PASSED: Identify UUID List", ret);
+	log_result(ret, "Identify UUID List", "\n");
 
 	printf("\nLogs\n");
 	printf("  SMART: Current temperature:%d percent used:%d%%\n", temp,
 		smart.percent_used);
 	ret = nvme_get_log_sanitize(fd, true, &sanlog);
-	printf("%s: %x\n", ret ? "ERROR: Sanitize Log" : "PASSED: Sanitize Log", ret);
+	log_result(ret, "Sanitize Log", "\n");
 	ret = nvme_get_log_reservation(fd, true, &resvnotify);
-	printf("%s: %x\n", ret ? "ERROR: Reservation Log" : "PASSED: Reservation Log", ret);
+	log_result(ret, "Reservation Log", "\n");
 	ret = nvme_get_log_ana_groups(fd, true, sizeof(buf), analog);
-	printf("%s: %x\n", ret ? "ERROR: ANA Groups" : "PASSED: ANA Groups", ret);
+	log_result(ret, "ANA Groups", "\n");
 	ret = nvme_get_log_endurance_group(fd, 0, &eglog);
-	printf("%s: %x\n", ret ? "ERROR: Endurance Group" : "PASSED: Endurance Group", ret);
+	log_result(ret, "Endurance Group", "\n");
 	ret = nvme_get_log_telemetry_ctrl(fd, true, 0, sizeof(buf), telem);
-	printf("%s: %x\n", ret ? "ERROR: Telemetry Controller" : "PASSED: Telemetry Controller", ret);
+	log_result(ret, "Telemetry Controller", "\n");
 	ret = nvme_get_log_device_self_test(fd, &st);
-	printf("%s: %x\n", ret ? "ERROR: Device Self Test" : "PASSED: Device Self Test", ret);
+	log_result(ret, "Device Self Test", "\n");
 	ret = nvme_get_log_cmd_effects(fd, NVME_CSI_NVM, &cfx);
-	printf("%s: %x\n", ret ? "ERROR: Command Effects" : "PASSED: Command Effects", ret);
+	log_result(ret, "Command Effects", "\n");
 	ret = nvme_get_log_changed_ns_list(fd, true, &ns_list);
-	printf("%s: %x\n", ret ? "ERROR: Change NS List" : "PASSED: Change NS List", ret);
+	log_result(ret, "Change NS List", "\n");
 	ret = nvme_get_log_fw_slot(fd, true, &fw);
-	printf("%s: %x\n", ret ? "ERROR: FW Slot" : "PASSED: FW Slot", ret);
+	log_result(ret, "FW Slot", "\n");
 	ret = nvme_get_log_error(fd, 64, true, error);
-	printf("%s: %x\n", ret ? "ERROR: Error Log" : "PASSED: Error Log", ret);
+	log_result(ret, "Error Log", "\n");
 	printf("\nFeatures\n");
 	ret = nvme_get_features_arbitration(fd, sel, &result);
-	if (!ret)
-		printf("  Arbitration:%x\n", result);
-	else if (ret > 0)
-		printf("  ERROR: Arbitration:%x\n", ret);
+	log_result(ret, "Arbitration", ":%x\n", result);
 	ret = nvme_get_features_power_mgmt(fd, sel, &result);
-	if (!ret)
-		printf("  Power Management:%x\n", result);
-	else if (ret > 0)
-		printf("  ERROR: Power Management:%x\n", ret);
+	log_result(ret, "Power Management", ":%x\n", result);
 	ret = nvme_get_features_temp_thresh(fd, sel, &result);
-	if (!ret)
-		printf("  Temperature Threshold:%x\n", result);
-	else if (ret > 0)
-		printf("  ERROR: Temperature Threshold:%x\n", ret);
+	log_result(ret, "Temperature Threshold", ":%x\n", result);
 	ret = nvme_get_features_err_recovery(fd, sel, &result);
-	if (!ret)
-		printf("  Error Recovery:%x\n", result);
-	else if (ret > 0)
-		printf("  ERROR: Error Recovery:%x\n", ret);
+	log_result(ret, "Error Recovery", ":%x\n", result);
 	ret = nvme_get_features_volatile_wc(fd, sel, &result);
-	if (!ret)
-		printf("  Volatile Write Cache:%x\n", result);
-	else if (ret > 0)
-		printf("  ERROR: Volatile Write Cache:%x\n", ret);
+	log_result(ret, "Volatile Write Cache", ":%x\n", result);
 	ret = nvme_get_features_num_queues(fd, sel, &result);
-	if (!ret)
-		printf("  Number of Queues:%x\n", result);
-	else if (ret > 0)
-		printf("  ERROR: Number of Queues:%x\n", ret);
+	log_result(ret, "Number of Queues", ":%x\n", result);
 	ret = nvme_get_features_irq_coalesce(fd, sel, &result);
-	if (!ret)
-		printf("  IRQ Coalescing:%x\n", result);
-	else if (ret > 0)
-		printf("  ERROR: IRQ Coalescing:%x\n", ret);
+	log_result(ret, "IRQ Coalescing", ":%x\n", result);
 	ret = nvme_get_features_write_atomic(fd, sel, &result);
-	if (!ret)
-		printf("  Write Atomic:%x\n", result);
-	else if (ret > 0)
-		printf("  ERROR: Write Atomic:%x\n", ret);
+	log_result(ret, "Write Atomic", ":%x\n", result);
 	ret = nvme_get_features_async_event(fd, sel, &result);
-	if (!ret)
-		printf("  Asycn Event Config:%x\n", result);
-	else if (ret > 0)
-		printf("  ERROR: Asycn Event Config:%x\n", ret);
+	log_result(ret, "Asycn Event Config", ":%x\n", result);
 	ret = nvme_get_features_hctm(fd, sel, &result);
-	if (!ret)
-		printf("  HCTM:%x\n", result);
-	else if (ret > 0)
-		printf("  ERROR: HCTM:%x\n", ret);
+	log_result(ret, "HCTM", ":%x\n", result);
 	ret = nvme_get_features_nopsc(fd, sel, &result);
-	if (!ret)
-		printf("  NOP Power State Config:%x\n", result);
-	else if (ret > 0)
-		printf("  ERROR: NOP Power State Configrbitration:%x\n", ret);
+	log_result(ret, "NOP Power State Config", ":%x\n", result);
 	ret = nvme_get_features_rrl(fd, sel, &result);
-	if (!ret)
-		printf("  Read Recover Levels:%x\n", result);
-	else if (ret > 0)
-		printf("  ERROR: Read Recover Levels:%x\n", ret);
+	log_result(ret, "Read Recover Levels", ":%x\n", result);
 	ret = nvme_get_features_lba_sts_interval(fd, sel, &result);
-	if (!ret)
-		printf("  LBA Status Interval:%x\n", result);
-	else if (ret > 0)
-		printf("  ERROR: LBA Status Interval:%x\n", ret);
+	log_result(ret, "LBA Status Interval", ":%x\n", result);
 	ret = nvme_get_features_sanitize(fd, sel, &result);
-	if (!ret)
-		printf("  Sanitize:%x\n", result);
-	else if (ret > 0)
-		printf("  ERROR: SW Progress Marker:%x\n", ret);
+	log_result(ret, "Sanitize", ":%x\n", result);
 	ret = nvme_get_features_sw_progress(fd, sel, &result);
-	if (!ret)
-		printf("  SW Progress Marker:%x\n", result);
-	else if (ret > 0)
-		printf("  ERROR: Sanitize:%x\n", ret);
+	log_result(ret, "SW Progress Marker", ":%x\n", result);
 	ret = nvme_get_features_resv_mask(fd, sel, &result);
-	if (!ret)
-		printf("  Reservation Mask:%x\n", result);
-	else if (ret > 0)
-		printf("  ERROR: Reservation Mask:%x\n", ret);
+	log_result(ret, "Reservation Mask", ":%x\n", result);
 	ret = nvme_get_features_resv_persist(fd, sel, &result);
-	if (!ret)
-		printf("  Reservation Persistence:%x\n", result);
-	else if (ret > 0)
-		printf("  ERROR: Reservation Persistence:%x\n", ret);
+	log_result(ret, "Reservation Persistence", ":%x\n", result);
 	return 0;
 }
 
@@ -235,21 +205,12 @@ static int test_namespace(nvme_ns_t n)
 		1 << ns.lbaf[flbas].ds);
 
 	ret = nvme_identify_allocated_ns(fd, nsid, &allocated);
-	if (!ret)
-		printf("  Identify allocated ns\n");
-	else
-		printf("  ERROR: Identify allocated ns:%x\n", ret);
+	log_result(ret, "Identify allocated ns", "\n");
 	ret = nvme_identify_ns_descs(fd, nsid,  &descs);
-	if (!ret)
-		printf("  Identify NS Descriptors\n");
-	else
-		printf("  ERROR: Identify NS Descriptors:%x\n", ret);
+	log_result(ret, "Identify NS Descriptors", "\n");
 	ret = nvme_get_features_write_protect(fd, nsid,
 		NVME_GET_FEATURES_SEL_CURRENT, &result);
-	if (!ret)
-		printf("  Write Protect:%x\n", result);
-	else if (ret > 0)
-		printf("  ERROR: Write Protect:%x\n", ret);
+	log_result(ret, "Write Protect", ":%x\n", result);
 	return 0;
 }
 ```

**Comment by Arunpandian15** [comment]
We can go ahead with above pointed change @igaw. I am ok with it.

**Comment by Arunpandian15** [comment]
I will close this PR and raise new PR for above suggestion.

**Pull request closed without merging**
