### PR TITLE
ioctl: Modify identify command argument based on spec

### PR DESCRIPTION
**Pull request by sc108-lee**
CNS Specific identifier presents all names below for DWORD11 bits [15:00]
    NVM Set Identifier(NVM Set List (04h))
    Domain Identifier(Domain List (18h))
    Endurance Group Identifier(Endurance Group List (19h))

Signed-off-by: Steven Seungcheol Lee <sc108.lee@samsung.com>

### CODE REVIEW

**Comment by igaw** [comment]
Looks good, though I would like to get @hreinecke's #150 sorted out first.

**Comment by igaw** [comment]
Can you please rebase this PR? As expected it conflicts with the changes from #150. Thanks!

**Comment by sc108-lee** [comment]
@igaw Thanks for the notice rebased :)

**Comment by sc108-lee** [comment]
merged into #166

**Pull request closed without merging**
