### PR TITLE
types: Fix EOM header optional data present fields definition

### PR DESCRIPTION
**Pull request by ikegami-t**
Defined eye data present as bit 0 and printable eye present as bit 1. Fixed eye data present to bit 1 and printable eye present to bit 0. Add the optional data present reserved filed definition and macros to get.

### CODE REVIEW

**Comment by ikegami-t** [comment]
Note: The existing NVME_EOM_EYE_DATA_PRESENT and NVME_EOM_PRINTABLE_EYE_PRESENT macros have been changed.

**Review by bpaupore-wdc — COMMENTED** [review]
Change seem mostly good to me, though wouldn't removing the original enums cause backwards-compatibility issues?

I'm not sure if this feature is new enough to just do it anyways, or if renaming the macros and fixing but keeping the original definitions would be best.

**Comment by igaw** [comment]
I agree, better leave the old enums around and avoid breakage.  Just add a 'deprecated' comment to them.

**Comment by ikegami-t** [comment]
Thanks for your review comments. Just fixed the patch as mentioned.

**Review by bpaupore-wdc — APPROVED** [review]

**Comment by igaw** [comment]
Thanks!

**Pull request merged**
