### PR TITLE
CI: use cibuildwheel

### PR DESCRIPTION
**Pull request by glimchb**
### === This change is not ready yet ===
Signed-off-by: Boris Glimcher <Boris.Glimcher@emc.com>

### CODE REVIEW

**Comment by igaw** [comment]
Can you rebase this on the master. Patch two is already merged. And please make two commits for the  CI changes and meson.build change with an explanation in the commit message.

**Comment by glimchb** [comment]
not sure about `link_with`... figuring this out still...

**Comment by igaw** [comment]
FWIW, I am not really convinced that we are building the Python extension correctly. I noticed that we have in source tree artifices after the build which is a clear indication something is wrong. I haven't found time to really try to figure out what's going on.

**Comment by glimchb** [comment]
@igaw I agree, something is not 100% there, just learning bit by bit how it's done properly

**Comment by igaw** [comment]
Could you add some explanation to the commit message why this is needed?

**Pull request closed without merging**
