### PR TITLE
Cleanups for release candidate

### PR DESCRIPTION
**Pull request by hreinecke**
Some minor cleanups for RC; removing an obsolete function and updating documentation for fabrics.h

### CODE REVIEW

**Comment by igaw** [comment]
You can also delete the docs for nvmf_add_ctrl_opts and also drop it from libnvme.map

**Comment by hreinecke** [comment]
Fixed now.

**Comment by igaw** [comment]
and doc/man/nvmf_add_ctrl_opts.2  should be removed from the meson file as well IIRC

**Comment by igaw** [comment]
wrong memory :)

**Pull request merged**
