### PR TITLE
mi: Cleanup nvme_mi_mi_config_get() to nvme_mi_get_mi_config()

### PR DESCRIPTION
**Pull request by ikegami-t**

### CODE REVIEW

**Comment by ikegami-t** [comment]
Changes for the issue #206.

**Comment by igaw** [comment]
@jk-ozlabs

**Comment by igaw** [comment]
My take on this, we will do this type of work for a major version update, e.g. libnvme 2.0.

**Comment by jk-ozlabs** [comment]
Nack on this one. The `nvme_mi_mi_` prefix is intentional: we use this for all of the `nvme_mi_` functions that send MI-type messages. So we have:

 * `nvme_mi_mi_` for the MI commands sent over MI; and
 * `nvme_mi_admin` for the Admin commands sent over MI

This is documented at: https://github.com/linux-nvme/libnvme/blob/42ac4535963556610a5bba8d1277c5a398a6ed5a/src/nvme/mi.h#L35-L44

**Comment by igaw** [comment]
True, I forgot that we already discussed this. Let's keep it as it is.

**Comment by jk-ozlabs** [comment]
(and the `config_get` is a direct reference to the MI Configuration Get command; not sure if we want to apply the verb-noun ordering to this one...)

**Comment by ikegami-t** [comment]
Thanks for your comments. I could understand them. By the way seems the PCIe commands over MI not implemented yet. (Also seems the mi resp status NVME_MI_RESP_PCIE_INACCESSIBLE is for the unimplemented command.)

**Comment by jk-ozlabs** [comment]
Yes, that's correct - I haven't done any work on the PCIe command-set. It's optional in the spec, and I don't know whether any of the device I have actually support it!

Is this something you're looking for, to be implemented?

**Comment by ikegami-t** [comment]
Thanks for the confirmation. No I thought to confirm if just my understanding for the PICe command-set support implementaton is correct or not. (I am also not sure if my device supported it.)

**Pull request closed without merging**
