### PR TITLE
For upstream/tp4095

### PR DESCRIPTION
**Pull request by sc108-lee**
Added NVM Command Set id-ns
updates for TP 4095 Namespace Capability Reporting 2021.06.28 - Ratified

### CODE REVIEW

**Comment by igaw** [comment]
Can you please rebase this PR? There are conflicts due to recent changes. Thanks!

**Comment by sc108-lee** [comment]
since the changes are conflict with #161 
rebased on #161 
PR merged into this

**Comment by igaw** [comment]
@hreinecke as this PR is changing the nvme_identify_args layout once again we should get this in soon. Any thoughts?

**Comment by igaw** [comment]
@sc108-lee could you rebase and update it to the current HEAD. I suppose we should get this in now.

**Comment by sc108-lee** [comment]
@igaw  rebased & added one more commit that remove domid from get log (using lsi field)

**Comment by igaw** [comment]
- Whitespace fixes
- dropping libnvme.rst and man pages updates
- fixed compile issues with first patch (don't drop NVME_DOMID_NONE too early)
- fixed commit message text

**Comment by igaw** [comment]
Hmm, I think I was too quick with the merge. The last patch looks strange:

```patch
@@ -1846,8 +1831,7 @@ static inline int nvme_get_log_media_unit_stat(int fd, __u16 domid,
                .len = sizeof(*mus),
                .nsid = NVME_NSID_NONE,
                .csi = NVME_CSI_NVM,
-               .lsi = NVME_LOG_LSI_NONE,
-               .domid = domid,
+               .lsi = domid,
                .lsp = NVME_LOG_LSP_NONE,
                .uuidx = NVME_UUID_NONE,

```

**Comment by sc108-lee** [comment]
@igaw  no worries, it was doing nothing for domid see blow.
https://github.com/linux-nvme/libnvme/blob/80db165b129ac59f7779b69bbe5c37bbb5ac7026/src/nvme/ioctl.c#L401

and also it should be input inside of lsi as I mentioned in commit msg

Check the spec 2.0a Figure 198: Get Log Page – Command Dword 11

**Comment by igaw** [comment]
Just read up in the spec. I didn't expect that the Log Specific Identifier was overloaded. Your change looks correct.

**Pull request merged**
